Blog/ViewModels/WizardViewModels/Step1ViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Blog.ViewModels.WizardViewModels
{
    public class Step1ViewModel
    {
        [Required(ErrorMessage = "El nombre es requerido")]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "Los apellidos son requeridos")]
        public string Apellidos { get; set; }
    }
}

Blog/ViewModels/WizardViewModels/Step2ViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Blog.ViewModels.WizardViewModels
{
    public class Step2ViewModel
    {
        [Required(ErrorMessage = "El DNI es requerido")]
        [RegularExpression(@"^\d{8}[a-zA-Z]$", ErrorMessage = "El DNI no es válido")]
        public string DNI { get; set; }

        [Required(ErrorMessage = "La dirección es requerida")]
        public string Direccion { get; set; }

        [Required(ErrorMessage = "La provincia es requerida")]
        public string Provincia { get; set; }

        [Required(ErrorMessage = "El municipio es requerido")]
        [ProvinceValidator] // Aplicando el Validator que hemos hecho
        public string Municipio { get; set; }
    }

    public class ProvinceValidator : ValidationAttribute
    {
        protected override ValidationResult IsValid(object value, ValidationContext validationContext)
        {
            var formulario = (Step2ViewModel)validationContext.ObjectInstance;

            // Validar la relación entre municipio y provincia
            if (formulario.Municipio == "MunicipioEjemplo" && formulario.Provincia != "ProvinciaEjemplo")
            {
                return new ValidationResult("El municipio seleccionado no corresponde a la provincia seleccionada.");
            }

            return ValidationResult.Success;
        }
    }
}

Blog/ViewModels/WizardViewModels/Step3ViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Blog.ViewModels.WizardViewModels
{
    public class Step3ViewModel
    {
        [Required(ErrorMessage = "El número de cuenta es requerido")]
        public string NumeroCuenta { get; set; }

        [Required(ErrorMessage = "Debes aceptar los términos y condiciones")]
        [Display(Name = "Acepto los términos y condiciones")]
        public bool AceptarTerminos { get; set; }
    }
}

Blog/ViewModels/WizardViewModels/WizardViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Blog.ViewModels.WizardViewModels
{
    public class WizardViewModel
    {
        public Step1ViewModel Step1 { get; set; }

        public Step2ViewModel Step2 { get; set; }

        public Step3ViewModel Step3 { get; set; }

        public WizardStep WizardStepState { get; set; }
    }

    public enum WizardStep
    {
        STEP1,
        STEP2,
        STEP3,
    }
}

Blog/Controllers/WizardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog.Controllers
{
    public class WizardController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        // GET: Wizard
        public ActionResult Step1()
        {
            var step1ViewModel = new ViewModels.WizardViewModels.WizardViewModel()
            {
                Step1 = new ViewModels.WizardViewModels.Step1ViewModel(),
                WizardStepState = ViewModels.WizardViewModels.WizardStep.STEP1
            };

            return View(step1ViewModel);
        }

        [HttpPost]
        public ActionResult Step2(ViewModels.WizardViewModels.WizardViewModel wizardViewModel)
        {
            if (ModelState.IsValid)
            {
                Session["Step1"] = wizardViewModel.Step1;

                wizardViewModel.Step2 = new ViewModels.WizardViewModels.Step2ViewModel();

                wizardViewModel.WizardStepState = ViewModels.WizardViewModels.WizardStep.STEP2;

                return View("Step2", wizardViewModel);
            }

            return View("Step1", wizardViewModel);
        }

        [HttpPost]
        public ActionResult Step3(ViewModels.WizardViewModels.WizardViewModel wizardViewModel)
        {
            if (ModelState.IsValid)
            {
                Session["Step2"] = wizardViewModel.Step2;

                wizardViewModel.Step3 = new ViewModels.WizardViewModels.Step3ViewModel();

                wizardViewModel.WizardStepState = ViewModels.WizardViewModels.WizardStep.STEP3;

                return View("Step3", wizardViewModel);
            }

            return View("Step2", wizardViewModel);
        }

        [HttpPost]
        public ActionResult Finish(ViewModels.WizardViewModels.WizardViewModel wizardViewModel)
        {
            if (ModelState.IsValid)
            {
                Session["Step3"] = wizardViewModel.Step3;

                var step1Data = (ViewModels.WizardViewModels.Step1ViewModel)Session["Step1"];
                var step2Data = (ViewModels.WizardViewModels.Step2ViewModel)Session["Step2"];
                var step3Data = wizardViewModel.Step3;

                Session.Remove("Step1");
                Session.Remove("Step2");
                Session.Remove("Step3");

                return RedirectToAction("Index");
            }

            return View("Step3", wizardViewModel);
        }
    }
}

Blog/Views/Wizard/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

Blog/Views/Wizard/Step1.cshtml
@model Blog.ViewModels.WizardViewModels.WizardViewModel

@{
    ViewBag.Title = "Step1";
}

<h2>Step1</h2>


@using (Html.BeginForm("Step2", "Wizard", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Step1ViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Step1.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Step1.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Step1.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Step1.Apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Step1.Apellidos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Step1.Apellidos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Next Step" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Blog/Views/Wizard/Step2.cshtml
@model Blog.ViewModels.WizardViewModels.WizardViewModel

@{
    ViewBag.Title = "Step2";
}

<h2>Step2</h2>


@using (Html.BeginForm("Step3", "Wizard", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Step2ViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Step2.DNI, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Step2.DNI, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Step2.DNI, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Step2.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Step2.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Step2.Direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Next Step" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Blog/Views/Wizard/Step3.cshtml
@model Blog.ViewModels.WizardViewModels.WizardViewModel

@{
    ViewBag.Title = "Step3";
}

<h2>Step3</h2>


@using (Html.BeginForm("Finish", "Wizard", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Step3ViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Step3.NumeroCuenta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Step3.NumeroCuenta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Step3.NumeroCuenta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Step3.AceptarTerminos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Step3.AceptarTerminos)
                    @Html.ValidationMessageFor(model => model.Step3.AceptarTerminos, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Finish" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}